name = "MISAlgorithms"
uuid = "405e750c-c8cf-11e9-3887-a572dd575b1a"
authors = ["JinGuo Liu"]
version = "0.1.0"

[deps]
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
